"""Added login credentials

Revision ID: 36fbaa65f7b4
Revises: f01b8e1a7950
Create Date: 2023-08-23 20:59:59.355677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36fbaa65f7b4'
down_revision = 'f01b8e1a7950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credentials_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_credentials_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credentials_username'))
        batch_op.drop_index(batch_op.f('ix_credentials_email'))

    op.drop_table('credentials')
    # ### end Alembic commands ###
