"""Added owner table

Revision ID: 61915b5dfe56
Revises: 3911489467b9
Create Date: 2023-08-16 19:22:00.765314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61915b5dfe56'
down_revision = '3911489467b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owners')
    # ### end Alembic commands ###
